import { Item, User, Claim, Message } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Johnson',
    email: 'sarah.j@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    phone: '+1 555-0123',
  },
  {
    id: 'user-2',
    name: 'Mike Chen',
    email: 'mike.c@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    phone: '+1 555-0124',
  },
  {
    id: 'user-3',
    name: 'Emily Rodriguez',
    email: 'emily.r@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    phone: '+1 555-0125',
  },
  {
    id: 'user-4',
    name: 'James Wilson',
    email: 'james.w@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    phone: '+1 555-0126',
  },
  {
    id: 'user-5',
    name: 'Lisa Park',
    email: 'lisa.p@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    phone: '+1 555-0127',
  },
];

export const mockItems: Item[] = [
  {
    id: 'item-1',
    type: 'lost',
    title: 'Black Leather Wallet',
    description: 'Lost my black leather wallet near the library. Contains student ID, credit cards, and some cash. Has a small tear on the left corner.',
    category: 'Wallet',
    location: 'Library',
    date: '2024-02-08',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
    status: 'active',
    tags: ['Wallet', 'Black', 'Leather', 'Cards'],
    verificationQuestion: 'What is the color of the card holder inside?',
    userId: 'user-1',
    user: mockUsers[0],
    createdAt: '2024-02-08T10:30:00Z',
  },
  {
    id: 'item-2',
    type: 'found',
    title: 'iPhone 13 Pro',
    description: 'Found an iPhone 13 Pro in the cafeteria. Blue color with a clear case. Screen has a small crack on the top right.',
    category: 'Phone',
    location: 'Cafeteria',
    date: '2024-02-09',
    imageUrl: 'https://images.unsplash.com/photo-1592286927505-c4bd7a40b9b6?w=800&q=80',
    status: 'active',
    tags: ['iPhone', 'Blue', 'Cracked Screen', 'Clear Case'],
    userId: 'user-2',
    user: mockUsers[1],
    createdAt: '2024-02-09T14:20:00Z',
  },
  {
    id: 'item-3',
    type: 'lost',
    title: 'Silver Keys with Red Keychain',
    description: 'Lost a set of keys with a red Toyota keychain. Has 3 keys including room key, bike lock key, and mailbox key.',
    category: 'Keys',
    location: 'Playground',
    date: '2024-02-07',
    imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&q=80',
    status: 'active',
    tags: ['Keys', 'Red Keychain', 'Toyota', 'Silver'],
    verificationQuestion: 'What brand is the car key?',
    userId: 'user-3',
    user: mockUsers[2],
    createdAt: '2024-02-07T16:45:00Z',
  },
  {
    id: 'item-4',
    type: 'found',
    title: 'Blue Backpack',
    description: 'Found a navy blue North Face backpack in classroom 204. Contains textbooks and a laptop.',
    category: 'Bag',
    location: 'Classroom',
    date: '2024-02-09',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    status: 'claimed',
    tags: ['Backpack', 'Blue', 'North Face', 'Laptop'],
    userId: 'user-4',
    user: mockUsers[3],
    createdAt: '2024-02-09T09:15:00Z',
  },
  {
    id: 'item-5',
    type: 'lost',
    title: 'Student ID Card',
    description: 'Lost my student ID card somewhere between the hostel and library. Name: Lisa Park, ID: 2021CS001',
    category: 'ID Card',
    location: 'Hostel',
    date: '2024-02-06',
    imageUrl: 'https://images.unsplash.com/photo-1614029655965-2464911905a4?w=800&q=80',
    status: 'active',
    tags: ['ID Card', 'Student', 'Lisa Park'],
    verificationQuestion: 'What is your student ID number?',
    userId: 'user-5',
    user: mockUsers[4],
    createdAt: '2024-02-06T11:30:00Z',
  },
  {
    id: 'item-6',
    type: 'found',
    title: 'Wireless Earbuds',
    description: 'Found AirPods Pro in the library study room. White charging case with some scratches.',
    category: 'Electronics',
    location: 'Library',
    date: '2024-02-10',
    imageUrl: 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800&q=80',
    status: 'active',
    tags: ['AirPods', 'White', 'Scratched', 'Electronics'],
    userId: 'user-1',
    user: mockUsers[0],
    createdAt: '2024-02-10T13:00:00Z',
  },
  {
    id: 'item-7',
    type: 'lost',
    title: 'Gray Hoodie',
    description: 'Lost my favorite gray Nike hoodie in the gym. Size M, has a small coffee stain on the sleeve.',
    category: 'Other',
    location: 'Other',
    date: '2024-02-08',
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80',
    status: 'active',
    tags: ['Hoodie', 'Gray', 'Nike', 'Size M'],
    verificationQuestion: 'What size is the hoodie?',
    userId: 'user-2',
    user: mockUsers[1],
    createdAt: '2024-02-08T17:20:00Z',
  },
  {
    id: 'item-8',
    type: 'found',
    title: 'Water Bottle',
    description: 'Found a stainless steel water bottle near the cafeteria entrance. Has some stickers on it.',
    category: 'Other',
    location: 'Cafeteria',
    date: '2024-02-09',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80',
    status: 'active',
    tags: ['Water Bottle', 'Steel', 'Stickers'],
    userId: 'user-3',
    user: mockUsers[2],
    createdAt: '2024-02-09T12:40:00Z',
  },
];

export const mockClaims: Claim[] = [
  {
    id: 'claim-1',
    itemId: 'item-4',
    claimantId: 'user-2',
    claimant: mockUsers[1],
    status: 'approved',
    verificationAnswer: 'Chemistry and Physics textbooks',
    message: 'This is my backpack! I left it in classroom 204 after my morning class.',
    otp: '4821',
    createdAt: '2024-02-09T10:30:00Z',
    item: mockItems[3],
  },
  {
    id: 'claim-2',
    itemId: 'item-2',
    claimantId: 'user-5',
    claimant: mockUsers[4],
    status: 'pending',
    message: 'I think this might be my phone. I lost it yesterday in the cafeteria.',
    createdAt: '2024-02-09T15:00:00Z',
    item: mockItems[1],
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    claimId: 'claim-1',
    senderId: 'user-2',
    sender: mockUsers[1],
    content: 'Hi! Is the backpack still available?',
    timestamp: '2024-02-09T10:35:00Z',
  },
  {
    id: 'msg-2',
    claimId: 'claim-1',
    senderId: 'user-4',
    sender: mockUsers[3],
    content: 'Yes! Can you describe what\'s inside to verify?',
    timestamp: '2024-02-09T10:37:00Z',
  },
  {
    id: 'msg-3',
    claimId: 'claim-1',
    senderId: 'user-2',
    sender: mockUsers[1],
    content: 'It has my Chemistry and Physics textbooks, and a Dell laptop.',
    timestamp: '2024-02-09T10:40:00Z',
  },
  {
    id: 'msg-4',
    claimId: 'claim-1',
    senderId: 'user-4',
    sender: mockUsers[3],
    content: 'Perfect! That matches. I\'ve approved your claim. Here\'s your OTP: 4821. Let\'s meet at the library tomorrow at 2 PM?',
    timestamp: '2024-02-09T10:42:00Z',
  },
  {
    id: 'msg-5',
    claimId: 'claim-1',
    senderId: 'user-2',
    sender: mockUsers[1],
    content: 'Sounds great! See you then. Thank you so much!',
    timestamp: '2024-02-09T10:45:00Z',
  },
];

export const adminUser: User = {
  id: 'admin-1',
  name: 'Admin User',
  email: 'admin@university.edu',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
};
